// <auto-generated />
using Labb3_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb3_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427120010_edit_database_prop")]
    partial class edit_database_prop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb3_API.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Konsten att bygga logik med C# och .NET.",
                            Title = "Programmering"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Allt från snabba pister till pudersnö i Alperna.",
                            Title = "Skidåkning"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Experimenterande i köket med smaker från hela världen.",
                            Title = "Matlagning"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Träning och tävling inom agility, lydnad och sök.",
                            Title = "Hundsport"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Konsten att fånga ljus och ögonblick med digital systemkamera.",
                            Title = "Fotografering"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Strategiska sällskapsspel, från enkla klassiker till tunga Euro-games.",
                            Title = "Brädspel"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Allt från styrkelyft på gymmet till löpning i skogen.",
                            Title = "Träning"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.InterestPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("InterestPersons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 1,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 3,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 1,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 5,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 7,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 8,
                            InterestId = 4,
                            PersonId = 4
                        },
                        new
                        {
                            Id = 9,
                            InterestId = 6,
                            PersonId = 4
                        },
                        new
                        {
                            Id = 10,
                            InterestId = 1,
                            PersonId = 5
                        },
                        new
                        {
                            Id = 11,
                            InterestId = 7,
                            PersonId = 5
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestPersonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestPersonId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestPersonId = 1,
                            Url = "https://learn.microsoft.com/dotnet"
                        },
                        new
                        {
                            Id = 2,
                            InterestPersonId = 2,
                            Url = "https://www.skistar.com"
                        },
                        new
                        {
                            Id = 3,
                            InterestPersonId = 3,
                            Url = "https://stackoverflow.com"
                        },
                        new
                        {
                            Id = 4,
                            InterestPersonId = 4,
                            Url = "https://www.tasteline.com"
                        },
                        new
                        {
                            Id = 5,
                            InterestPersonId = 5,
                            Url = "https://www.github.com"
                        },
                        new
                        {
                            Id = 6,
                            InterestPersonId = 6,
                            Url = "https://www.dpreview.com"
                        },
                        new
                        {
                            Id = 7,
                            InterestPersonId = 7,
                            Url = "https://www.styrkelabbet.se"
                        },
                        new
                        {
                            Id = 8,
                            InterestPersonId = 8,
                            Url = "https://www.skk.se"
                        },
                        new
                        {
                            Id = 9,
                            InterestPersonId = 9,
                            Url = "https://boardgamegeek.com"
                        },
                        new
                        {
                            Id = 10,
                            InterestPersonId = 10,
                            Url = "https://www.codewars.com"
                        },
                        new
                        {
                            Id = 11,
                            InterestPersonId = 11,
                            Url = "https://www.runnersworld.se"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Anna Andersson",
                            PhoneNumber = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Björn Berg",
                            PhoneNumber = "0739876543"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cecilia Ceder",
                            PhoneNumber = "0700112233"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Daniel Duva",
                            PhoneNumber = "0763425138"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Erik Ek",
                            PhoneNumber = "0765554433"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.InterestPerson", b =>
                {
                    b.HasOne("Labb3_API.Models.Interest", "Interest")
                        .WithMany("InterestPersons")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb3_API.Models.Person", "Person")
                        .WithMany("InterestPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb3_API.Models.Link", b =>
                {
                    b.HasOne("Labb3_API.Models.InterestPerson", "InterestPerson")
                        .WithMany("Links")
                        .HasForeignKey("InterestPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterestPerson");
                });

            modelBuilder.Entity("Labb3_API.Models.Interest", b =>
                {
                    b.Navigation("InterestPersons");
                });

            modelBuilder.Entity("Labb3_API.Models.InterestPerson", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Labb3_API.Models.Person", b =>
                {
                    b.Navigation("InterestPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
